### Post
POST localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoibWF4YW1hZHF1bG92aWxraG9tam9uQGdtYWlsLmNvbSIsInN1YiI6Im1heGFtYWRxdWxvdmlsa2hvbWpvbkBnbWFpbC5jb20iLCJpYXQiOjE3NjU4ODM1ODAsImV4cCI6MTc2NTk2OTk4MH0.Y-zAGpSGj5GAKeuaTEwiJPAiG2hN3X7MjxSxBoTzPeY3i5XPY1LCziSceSjno7IA

{
  "orderNumber": 14,
  "nameUz": "jahon",
  "nameEn": "global",
  "nameRu": "мировой",
  "categoryKey": "jahon12"
}

###
POST localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "orderNumber": 2,
  "nameUz": "sport",
  "nameEn": "sports",
  "nameRu": "спорт",
  "categoryKey": "sport"
}

###
POST localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "orderNumber": 3,
  "nameUz": "texnologiya",
  "nameEn": "technology",
  "nameRu": "технология",
  "categoryKey": "tech"
}

###
POST localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "orderNumber": 4,
  "nameUz": "madaniyat",
  "nameEn": "culture",
  "nameRu": "культура",
  "categoryKey": "culture"
}

###
POST localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "orderNumber": 5,
  "nameUz": "iqtisod",
  "nameEn": "economy",
  "nameRu": "экономика",
  "categoryKey": "economy"
}

### UPDATE
PUT localhost:8080/category/update/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "nameUz": "jahon1",
  "nameEn": "global1",
  "nameRu": "мировой1",
  "categoryKey": "jahon 12"
}

### DELETE
DELETE localhost:8080/category/delete/5
Authorization: Bearer {{jwt}}

### GET
GET localhost:8080/category/getAll
Authorization: Bearer {{jwt}}


### GET
GET localhost:8080/category/getAllByLang
Accept-Language: RU
Authorization: Bearer {{jwt}}

