### Post create
POST localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Ali",
  "surname": "developer",
  "password": "ali",
  "roleList": ["ROLE_MODERATOR"],
  "username": "+998990001122"
}

###
POST localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Vali",
  "surname": "Valiyev",
  "password": "vali123",
  "roleList": ["ROLE_PUBLISHER"],
  "username": "+998901112233"
}

###
POST localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Aziz",
  "surname": "Azizov",
  "password": "aziz2024",
  "roleList": ["ROLE_MODERATOR"],
  "username": "+998907778899"
}

###
POST localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Jasur",
  "surname": "Jasurov",
  "password": "jasur777",
  "roleList": ["ROLE_MODERATOR"],
  "username": "+998931234500"
}

###
POST localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Sherzod",
  "surname": "Sherzodov",
  "password": "sherzod321",
  "roleList": ["ROLE_PUBLISHER"],
  "status": "ACTIVE",
  "username": "+998935550071"
}

### Update
PUT localhost:8080/profile/update/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Vali Valiyev Valijon",
  "surname": "Valiyev 11",
  "password": "vali123",
  "roleList": ["ROLE_MODERATOR", "ROLE_PUBLISHER"],
  "username": "+99890 00 00 00 00"
}


### Update
PUT localhost:8080/profile/update/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Test update id 3",
  "surname": "Valiyev 11",
  "password": "vali123",
  "roleList": ["ROLE_MODERATOR", "ROLE_PUBLISHER"],
  "username": "+99890 00 00 77 77"
}

### Post pagination
POST localhost:8080/profile/pagination?page=1&size=2
Authorization: Bearer {{jwt}}

### DELETE
DELETE localhost:8080/profile/delete/2
Authorization: Bearer {{jwt}}

### Get test
GET http://localhost:8080/
Authorization: Bearer {{jwt}}

### update password
PUT localhost:8080/profile/updatePassword/4/yyyyyyy
Authorization: Bearer {{jwt}}

