
### SMS Code

POST https://notify.eskiz.uz/api/auth/login
Content-Type: application/json

{
 "email" : "maxamadqulovilkhomjon@gmail.com",
  "password" : ""
}

### test


POST https://notify.eskiz.uz/api/message/sms/send
Content-Type: application/json
Authorization: Bearer ******************
{
  "mobile_phone": "+998970073922",
  "message": "Bu Eskiz dan test",
  "from": 4546

}

